import {
  Apps,
  Archive,
  Article,
  AutoStories,
  Book,
  Bookmark,
  BookmarkAdd,
  Bookmarks,
  BookOnline,
  Category,
  ChromeReaderMode,
  Collections,
  CollectionsBookmark,
  Folder,
  FolderOpen,
  FolderSpecial,
  ImportContacts,
  Inventory2,
  LibraryAdd,
  LibraryAddCheck,
  LibraryBooks,
  LocalLibrary,
  MenuBook,
  Newspaper,
  Style,
  ViewList,
  ViewModule,
} from "@mui/icons-material";

/** Icons for the bookshelf */
export const BookShelfIcons = [
  { key: "book", icon: <Book /> },
  { key: "menu-book", icon: <MenuBook /> },
  { key: "auto-stories", icon: <AutoStories /> },
  { key: "library-books", icon: <LibraryBooks /> },
  { key: "local-library", icon: <LocalLibrary /> },
  { key: "chrome-reader-mode", icon: <ChromeReaderMode /> },
  { key: "library-add", icon: <LibraryAdd /> },
  { key: "library-add-check", icon: <LibraryAddCheck /> },
  { key: "book-online", icon: <BookOnline /> },
  { key: "import-contacts", icon: <ImportContacts /> },
  { key: "article", icon: <Article /> },
  { key: "newspaper", icon: <Newspaper /> },
  { key: "collections-bookmark", icon: <CollectionsBookmark /> },
  { key: "collections", icon: <Collections /> },
  { key: "bookmark", icon: <Bookmark /> },
  { key: "bookmarks", icon: <Bookmarks /> },
  { key: "bookmark-add", icon: <BookmarkAdd /> },
  { key: "category", icon: <Category /> },
  { key: "style", icon: <Style /> },
  { key: "folder", icon: <Folder /> },
  { key: "folder-open", icon: <FolderOpen /> },
  { key: "folder-special", icon: <FolderSpecial /> },
  { key: "archive", icon: <Archive /> },
  { key: "inventory2", icon: <Inventory2 /> },
  { key: "view-list", icon: <ViewList /> },
  { key: "view-module", icon: <ViewModule /> },
  { key: "apps", icon: <Apps /> },
];
