// @ts-nocheck

// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**
	 *  Reads the current application settings.
	 * 
	 *  This is a **pure read**: it loads and normalizes the stored settings without
	 *  acquiring the file lock or writing back. A file hand-edited to an out-of-range
	 *  value is repaired in memory here and healed on disk at the next startup or write.
	 * 
	 *  # Arguments
	 * 
	 *  * `app` - The Tauri app handle, used to access the settings store.
	 * 
	 *  # Returns
	 * 
	 *  The normalized, valid [`AppSettings`].
	 * 
	 *  # Errors
	 * 
	 *  Returns an `Err` if the settings cannot be loaded.
	 */
	getSettings: () => typedError<AppSettings_Serialize, CommandError>(__TAURI_INVOKE("get_settings")),
	/**
	 *  Applies a partial settings change and returns the full merged settings.
	 * 
	 *  The `patch` carries only the changed leaves of a single category. The backend
	 *  deep-merges it into the current settings, validates the merged whole, persists it,
	 *  applies the reader/rendering values to the live container runtime, and broadcasts
	 *  a `settings-changed` event so other windows re-hydrate.
	 * 
	 *  # Arguments
	 * 
	 *  * `app` - The Tauri app handle.
	 *  * `patch` - The single-category partial change to apply.
	 *  * `state` - The application's runtime state.
	 *  * `lock` - The settings file lock serializing the read-modify-write.
	 * 
	 *  # Returns
	 * 
	 *  The full merged [`AppSettings`].
	 * 
	 *  # Errors
	 * 
	 *  Returns `Error::Settings` if the merged result is invalid (e.g. out of range),
	 *  or a persistence/emit error.
	 */
	setSettings: (patch: SettingsPatch) => typedError<AppSettings_Serialize, CommandError>(__TAURI_INVOKE("set_settings", { patch })),
	/**
	 *  Requests preloading of images around a specific index.
	 * 
	 *  This command can be called as the user navigates through a book to update
	 *  which images are prioritized for background loading.
	 * 
	 *  # Arguments
	 * 
	 *  * `index` - The current page index around which to preload.
	 *  * `buffer_size` - Optional. How many pages to preload in each direction.
	 *    Defaults to 10 if `None` is provided.
	 *  * `state` - A `tauri::State` holding the application's global `AppState`.
	 */
	requestPreloadAround: (index: number, bufferSize: number | null) => typedError<null, CommandError>(__TAURI_INVOKE("request_preload_around", { index, bufferSize })),
	/**
	 *  Opens a container file (e.g., ZIP, RAR) and retrieves a list of its contents.
	 * 
	 *  This function opens the container specified by the `path` and reads the list of file entries
	 *  within it.
	 * 
	 *  # Arguments
	 * 
	 *  * `path` - The file path to the container to open.
	 *  * `state` - A `tauri::State` holding the application's global `AppState`.
	 * 
	 *  # Returns
	 * 
	 *  A `Result` which is `Ok` with an `EntriesResult` struct containing the list of entry
	 *  names, a boolean indicating if the path is a directory, and a boolean indicating if it's a novel.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if:
	 *  * The container file cannot be opened (e.g., it does not exist or is corrupt).
	 *  * The `container` within the application state is unexpectedly missing.
	 */
	getEntriesInContainer: (path: string) => typedError<EntriesResult, CommandError>(__TAURI_INVOKE("get_entries_in_container", { path })),
	/**
	 *  Retrieves a list of all font families installed on the system.
	 * 
	 *  This function queries the system's font source to get a list of all available
	 *  font family names, which are then sorted alphabetically.
	 * 
	 *  # Returns
	 * 
	 *  A `Vec<String>` containing the sorted names of all installed font families.
	 *  If the system's font source cannot be accessed or no families are found,
	 *  it returns an empty vector.
	 */
	getFonts: () => __TAURI_INVOKE<string[]>("get_fonts"),
	/**
	 *  Retrieves the IDs of all tags associated with a specific book.
	 * 
	 *  # Arguments
	 * 
	 *  * `book_id` - The unique identifier of the book.
	 *  * `repo` - The managed tag repository state.
	 * 
	 *  # Returns
	 * 
	 *  A `Result` containing a vector of tag IDs.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	getBookTags: (bookId: number) => typedError<number[], CommandError>(__TAURI_INVOKE("get_book_tags", { bookId })),
	/**
	 *  Updates the tags associated with a specific book.
	 * 
	 *  # Arguments
	 * 
	 *  * `book_id` - The unique identifier of the book.
	 *  * `tag_ids` - A list of tag IDs to associate with the book.
	 *  * `repo` - The managed book repository state.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	updateBookTags: (bookId: number, tagIds: number[]) => typedError<null, CommandError>(__TAURI_INVOKE("update_book_tags", { bookId, tagIds })),
	/**
	 *  Retrieves a book by its unique ID.
	 * 
	 *  # Arguments
	 * 
	 *  * `id` - The unique identifier of the book.
	 *  * `repo` - The managed book repository state.
	 * 
	 *  # Returns
	 * 
	 *  A `Result` which is `Ok` containing an `Option<Book>`.
	 *  It evaluates to `Some(Book)` if a matching book is found, or `None` if no such book exists.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	getBook: (id: number) => typedError<{
	/**  The unique identifier for the book. */
	id: number,
	/**  The unique file path or directory path of the book. */
	file_path: string,
	/**  The type of the item ('file' or 'directory'). */
	item_type: string,
	/**  The display name of the book. */
	display_name: string,
	/**  The total number of pages in the book. */
	total_pages: number,
	/**  The optional identifier of the series this book belongs to. */
	series_id: number | null,
	/**  The optional order index of the book within its series. */
	series_order: number | null,
	/**  The optional file path to the thumbnail image of the book. */
	thumbnail_path: string | null,
} | null, CommandError>(__TAURI_INVOKE("get_book", { id })),
	/**
	 *  Retrieves a book by its unique file path.
	 * 
	 *  # Arguments
	 * 
	 *  * `file_path` - The unique file or directory path.
	 *  * `repo` - The managed book repository state.
	 * 
	 *  # Returns
	 * 
	 *  A `Result` which is `Ok` containing an `Option<Book>`.
	 *  It evaluates to `Some(Book)` if a matching book is found, or `None` if no such book exists.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	getBookByPath: (filePath: string) => typedError<{
	/**  The unique identifier for the book. */
	id: number,
	/**  The unique file path or directory path of the book. */
	file_path: string,
	/**  The type of the item ('file' or 'directory'). */
	item_type: string,
	/**  The display name of the book. */
	display_name: string,
	/**  The total number of pages in the book. */
	total_pages: number,
	/**  The optional identifier of the series this book belongs to. */
	series_id: number | null,
	/**  The optional order index of the book within its series. */
	series_order: number | null,
	/**  The optional file path to the thumbnail image of the book. */
	thumbnail_path: string | null,
} | null, CommandError>(__TAURI_INVOKE("get_book_by_path", { filePath })),
	/**
	 *  Retrieves a book along with its reading state by its unique ID.
	 * 
	 *  # Arguments
	 * 
	 *  * `id` - The unique identifier of the book.
	 *  * `repo` - The managed book repository state.
	 * 
	 *  # Returns
	 * 
	 *  A `Result` which is `Ok` containing an `Option<BookWithState>`.
	 *  It evaluates to `Some(BookWithState)` if a matching book is found,
	 *  or `None` if no such book exists in the repository.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	getBookWithStateById: (id: number) => typedError<{
	/**  The unique identifier for the book. */
	id: number,
	/**  The unique file path or directory path of the book. */
	file_path: string,
	/**  The type of the item ('file' or 'directory'). */
	item_type: string,
	/**  The display name of the book. */
	display_name: string,
	/**  The total number of pages in the book. */
	total_pages: number,
	/**  The optional identifier of the series this book belongs to. */
	series_id: number | null,
	/**  The optional order index of the book within its series. */
	series_order: number | null,
	/**  The optional file path to the thumbnail image of the book. */
	thumbnail_path: string | null,
	/**  The last read page index, if the book has been opened. */
	last_read_page_index: number | null,
	/**  The timestamp when the book was last opened, if any. */
	last_opened_at: string | null,
	/**  List of tag IDs associated with this book. */
	tag_ids?: number[],
} | null, CommandError>(__TAURI_INVOKE("get_book_with_state_by_id", { id })),
	/**
	 *  Registers a book or returns its ID if it already exists, without updating reading state.
	 * 
	 *  # Arguments
	 * 
	 *  * `file_path` - The unique file or directory path.
	 *  * `item_type` - The type of the item ('file' or 'directory').
	 *  * `display_name` - The display name of the book.
	 *  * `total_pages` - The total number of pages.
	 *  * `repo` - The managed book repository state.
	 *  * `app` - The Tauri AppHandle.
	 *  * `state` - The managed app state.
	 * 
	 *  # Returns
	 * 
	 *  A `Result` containing the ID of the registered book.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	registerBook: (filePath: string, itemType: string, displayName: string, totalPages: number) => typedError<number, CommandError>(__TAURI_INVOKE("register_book", { filePath, itemType, displayName, totalPages })),
	/**
	 *  Records the event of a book being opened, updating its last opened time.
	 * 
	 *  # Arguments
	 * 
	 *  * `file_path` - The unique file or directory path.
	 *  * `item_type` - The type of the item ('file' or 'directory').
	 *  * `display_name` - The display name of the book.
	 *  * `total_pages` - The total number of pages.
	 *  * `repo` - The managed book repository state.
	 *  * `app` - The Tauri AppHandle.
	 *  * `state` - The managed app state.
	 * 
	 *  # Returns
	 * 
	 *  A `Result` containing the ID of the book.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	recordBookOpened: (filePath: string, itemType: string, displayName: string, totalPages: number) => typedError<number, CommandError>(__TAURI_INVOKE("record_book_opened", { filePath, itemType, displayName, totalPages })),
	/**
	 *  Deletes a book by its unique ID.
	 * 
	 *  # Arguments
	 * 
	 *  * `id` - The unique identifier of the book to delete.
	 *  * `repo` - The managed book repository state.
	 *  * `app` - The Tauri AppHandle.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails.
	 */
	deleteBook: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("delete_book", { id })),
	/**
	 *  Clears the reading history for a specific book.
	 * 
	 *  # Arguments
	 * 
	 *  * `book_id` - The unique identifier of the book.
	 *  * `repo` - The managed book repository state.
	 *  * `app` - The Tauri AppHandle.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	clearReadingHistory: (bookId: number) => typedError<null, CommandError>(__TAURI_INVOKE("clear_reading_history", { bookId })),
	/**
	 *  Clears the reading history for all books in the library.
	 * 
	 *  # Arguments
	 * 
	 *  * `repo` - The managed book repository state.
	 *  * `app` - The Tauri AppHandle.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	clearAllReadingHistory: () => typedError<null, CommandError>(__TAURI_INVOKE("clear_all_reading_history")),
	/**
	 *  Retrieves recently read books, ordered by the most recently opened.
	 * 
	 *  # Arguments
	 * 
	 *  * `limit` - The maximum number of books to retrieve.
	 *  * `repo` - The managed book repository state.
	 * 
	 *  # Returns
	 * 
	 *  A `Result` containing a vector of `ReadBook` entities.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	getRecentlyReadBooks: (limit: number | null) => typedError<ReadBook[], CommandError>(__TAURI_INVOKE("get_recently_read_books", { limit })),
	/**
	 *  Updates the reading progress/state for a book.
	 * 
	 *  # Arguments
	 * 
	 *  * `state_data` - The `ReadingState` object sent from the frontend.
	 *  * `repo` - The managed book repository state.
	 *  * `app` - The Tauri AppHandle.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	updateReadingProgress: (stateData: ReadingState) => typedError<null, CommandError>(__TAURI_INVOKE("update_reading_progress", { stateData })),
	/**
	 *  Retrieves all books, including their reading states.
	 * 
	 *  # Arguments
	 * 
	 *  * `repo` - The managed book repository state.
	 * 
	 *  # Returns
	 * 
	 *  A `Result` containing a vector of `BookWithState` entities, or an error message string..
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	getAllBooksWithState: () => typedError<BookWithState[], CommandError>(__TAURI_INVOKE("get_all_books_with_state")),
	/**
	 *  Retrieves all books contained within a specific bookshelf, including their reading states.
	 * 
	 *  # Arguments
	 * 
	 *  * `bookshelf_id` - The ID of the bookshelf.
	 *  * `repo` - The managed book repository state.
	 * 
	 *  # Returns
	 * 
	 *  A `Result` containing a vector of `BookWithState` entities.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	getBooksWithStateByBookshelfId: (bookshelfId: number) => typedError<BookWithState[], CommandError>(__TAURI_INVOKE("get_books_with_state_by_bookshelf_id", { bookshelfId })),
	/**
	 *  Retrieves all books associated with a specific tag, including their reading states.
	 * 
	 *  # Arguments
	 * 
	 *  * `tag_id` - The unique identifier of the tag to filter by.
	 *  * `repo` - The managed tag repository state.
	 * 
	 *  # Returns
	 * 
	 *  A `Result` containing a vector of `BookWithState` entities.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	getBooksWithStateByTagId: (tagId: number) => typedError<BookWithState[], CommandError>(__TAURI_INVOKE("get_books_with_state_by_tag_id", { tagId })),
	/**
	 *  Retrieves all books belonging to a specific series, including their reading states.
	 * 
	 *  # Arguments
	 * 
	 *  * `series_id` - The unique identifier of the series to filter by.
	 *  * `repo` - The managed book repository state.
	 * 
	 *  # Returns
	 * 
	 *  A `Result` containing a vector of `BookWithState` entities.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	getBooksWithStateBySeriesId: (seriesId: number) => typedError<BookWithState[], CommandError>(__TAURI_INVOKE("get_books_with_state_by_series_id", { seriesId })),
	/**
	 *  Updates the series associated with a specific book.
	 * 
	 *  # Arguments
	 * 
	 *  * `book_id` - The unique identifier of the book.
	 *  * `series_id` - The unique identifier of the series to associate with the book, or `None` to remove.
	 *  * `repo` - The managed series repository state.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails.
	 */
	updateBookSeries: (bookId: number, seriesId: number | null) => typedError<null, CommandError>(__TAURI_INVOKE("update_book_series", { bookId, seriesId })),
	/**
	 *  Updates the `series_order` for a given list of book IDs.
	 * 
	 *  # Arguments
	 * 
	 *  * `book_ids` - A list of book IDs in the desired order.
	 *  * `repo` - The managed series repository state.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails.
	 */
	updateSeriesOrders: (bookIds: number[]) => typedError<null, CommandError>(__TAURI_INVOKE("update_series_orders", { bookIds })),
	/**
	 *  Creates a new bookshelf and returns its complete entity.
	 * 
	 *  # Arguments
	 * 
	 *  * `name` - The name of the new bookshelf.
	 *  * `icon_id` - The string identifier for the UI icon.
	 *  * `repo` - The managed bookshelf repository state.
	 * 
	 *  # Returns
	 * 
	 *  A `Result` containing the newly created `Bookshelf` entity.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	createBookshelf: (name: string, iconId: string) => typedError<Bookshelf, CommandError>(__TAURI_INVOKE("create_bookshelf", { name, iconId })),
	/**
	 *  Retrieves all bookshelves from the database.
	 * 
	 *  # Arguments
	 * 
	 *  * `repo` - The managed bookshelf repository state.
	 * 
	 *  # Returns
	 * 
	 *  A `Result` containing a vector of `Bookshelf` entities.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	getAllBookshelves: () => typedError<Bookshelf[], CommandError>(__TAURI_INVOKE("get_all_bookshelves")),
	/**
	 *  Adds a book to a specific bookshelf.
	 * 
	 *  # Arguments
	 * 
	 *  * `bookshelf_id` - The ID of the bookshelf.
	 *  * `book_id` - The ID of the book to add.
	 *  * `repo` - The managed bookshelf repository state.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	addBookToBookshelf: (bookshelfId: number, bookId: number) => typedError<null, CommandError>(__TAURI_INVOKE("add_book_to_bookshelf", { bookshelfId, bookId })),
	/**
	 *  Removes a book from a specific bookshelf.
	 * 
	 *  # Arguments
	 * 
	 *  * `bookshelf_id` - The ID of the bookshelf.
	 *  * `book_id` - The ID of the book to remove.
	 *  * `repo` - The managed bookshelf repository state.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails.
	 */
	removeBookFromBookshelf: (bookshelfId: number, bookId: number) => typedError<null, CommandError>(__TAURI_INVOKE("remove_book_from_bookshelf", { bookshelfId, bookId })),
	/**
	 *  Deletes a bookshelf from the database.
	 * 
	 *  # Arguments
	 * 
	 *  * `id` - The ID of the bookshelf to delete.
	 *  * `repo` - The managed bookshelf repository state.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails.
	 */
	deleteBookshelf: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("delete_bookshelf", { id })),
	/**
	 *  Creates a new series.
	 * 
	 *  # Arguments
	 * 
	 *  * `name` - The name of the new series.
	 *  * `repo` - The managed series repository state.
	 * 
	 *  # Returns
	 * 
	 *  A `Result` containing the ID of the newly created series.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	createSeries: (name: string) => typedError<number, CommandError>(__TAURI_INVOKE("create_series", { name })),
	/**
	 *  Retrieves all series from the database.
	 * 
	 *  # Arguments
	 * 
	 *  * `repo` - The managed series repository state.
	 * 
	 *  # Returns
	 * 
	 *  A `Result` containing a vector of `Series` entities.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	getAllSeries: () => typedError<Series[], CommandError>(__TAURI_INVOKE("get_all_series")),
	/**
	 *  Deletes a series by its ID.
	 * 
	 *  # Arguments
	 * 
	 *  * `id` - The ID of the series to delete.
	 *  * `repo` - The managed series repository state.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails.
	 */
	deleteSeries: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("delete_series", { id })),
	/**
	 *  Creates a new tag and returns its complete entity.
	 * 
	 *  # Arguments
	 * 
	 *  * `name` - The name of the new tag.
	 *  * `color_code` - The color code for the tag.
	 *  * `repo` - The managed tag repository state.
	 * 
	 *  # Returns
	 * 
	 *  A `Result` containing the newly created `Tag` entity.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	createTag: (name: string, colorCode: string) => typedError<Tag, CommandError>(__TAURI_INVOKE("create_tag", { name, colorCode })),
	/**
	 *  Retrieves all tags from the database.
	 * 
	 *  # Arguments
	 * 
	 *  * `repo` - The managed tag repository state.
	 * 
	 *  # Returns
	 * 
	 *  A `Result` containing a vector of `Tag` entities.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails
	 *  (e.g., due to a database error, connection issue, or query execution failure).
	 */
	getAllTags: () => typedError<Tag[], CommandError>(__TAURI_INVOKE("get_all_tags")),
	/**
	 *  Deletes a tag from the database.
	 * 
	 *  # Arguments
	 * 
	 *  * `id` - The ID of the tag to delete.
	 *  * `repo` - The managed tag repository state.
	 * 
	 *  # Errors
	 * 
	 *  This function will return an `Err` if the underlying repository operation fails.
	 */
	deleteTag: (id: number) => typedError<null, CommandError>(__TAURI_INVOKE("delete_tag", { id })),
	/**
	 *  Checks if the auto-updater is supported on the current platform/environment.
	 * 
	 *  Returns `true` if the updater is supported, `false` otherwise.
	 *  - Windows: Always supported.
	 *  - macOS: Always supported.
	 *  - Linux: Supported only if running as an AppImage (checked via `APPIMAGE` environment variable).
	 */
	isUpdaterSupported: () => __TAURI_INVOKE<boolean>("is_updater_supported"),
};

/* Types */
/**  Represents the root configuration of the application settings. */
export type AppSettings = AppSettings_Serialize | AppSettings_Deserialize;

/**  Represents the root configuration of the application settings. */
export type AppSettings_Deserialize = {
	/**  General application settings, including theming and fonts. */
	general?: GeneralSettings,
	/**  Settings related to the application's startup behavior. */
	startup?: StartupSettings,
	/**  Settings specific to the bookshelf (library) view. */
	bookshelf?: BookshelfSettings,
	/**  Settings for the file navigator and directory management. */
	fileNavigator?: FileNavigatorSettings,
	/**  Settings for reading content (both comics and novels). */
	reader?: ReaderSettings_Deserialize,
	/**  Settings related to user history and tracking. */
	history?: HistorySettings,
	/**  Settings related to the application's layout. */
	layout?: LayoutSettings,
};

/**  Represents the root configuration of the application settings. */
export type AppSettings_Serialize = {
	/**  General application settings, including theming and fonts. */
	general: GeneralSettings,
	/**  Settings related to the application's startup behavior. */
	startup: StartupSettings,
	/**  Settings specific to the bookshelf (library) view. */
	bookshelf: BookshelfSettings,
	/**  Settings for the file navigator and directory management. */
	fileNavigator: FileNavigatorSettings,
	/**  Settings for reading content (both comics and novels). */
	reader: ReaderSettings_Serialize,
	/**  Settings related to user history and tracking. */
	history: HistorySettings,
	/**  Settings related to the application's layout. */
	layout: LayoutSettings,
};

/**  Represents the application's visual theme. */
export type AppTheme = 
/**  Matches the operating system's theme preference. */
"system" | 
/**  Light color scheme. */
"light" | 
/**  Dark color scheme. */
"dark";

/**  Behavior when paging past the last/first page of a book. */
export type AutoOpenAdjacentBookMode = 
/**  Do nothing at the book boundary (stay on the page). */
"off" | 
/**  Ask for confirmation before opening the adjacent book. */
"ask" | 
/**  Open the adjacent book automatically. */
"auto";

/**  Represents a book entity in the database. */
export type Book = {
	/**  The unique identifier for the book. */
	id: number,
	/**  The unique file path or directory path of the book. */
	file_path: string,
	/**  The type of the item ('file' or 'directory'). */
	item_type: string,
	/**  The display name of the book. */
	display_name: string,
	/**  The total number of pages in the book. */
	total_pages: number,
	/**  The optional identifier of the series this book belongs to. */
	series_id: number | null,
	/**  The optional order index of the book within its series. */
	series_order: number | null,
	/**  The optional file path to the thumbnail image of the book. */
	thumbnail_path: string | null,
};

/**
 *  Represents a book along with its optional reading state.
 *  Useful for displaying book details whether it has been read or not.
 */
export type BookWithState = {
	/**  The unique identifier for the book. */
	id: number,
	/**  The unique file path or directory path of the book. */
	file_path: string,
	/**  The type of the item ('file' or 'directory'). */
	item_type: string,
	/**  The display name of the book. */
	display_name: string,
	/**  The total number of pages in the book. */
	total_pages: number,
	/**  The optional identifier of the series this book belongs to. */
	series_id: number | null,
	/**  The optional order index of the book within its series. */
	series_order: number | null,
	/**  The optional file path to the thumbnail image of the book. */
	thumbnail_path: string | null,
	/**  The last read page index, if the book has been opened. */
	last_read_page_index: number | null,
	/**  The timestamp when the book was last opened, if any. */
	last_opened_at: string | null,
	/**  List of tag IDs associated with this book. */
	tag_ids?: number[],
};

/**  Represents a bookshelf entity used to organize books. */
export type Bookshelf = {
	/**  The unique identifier for the bookshelf. */
	id: number,
	/**  The display name of the bookshelf. */
	name: string,
	/**  The string identifier for the UI icon (e.g., "folder"). */
	icon_id: string,
	/**  The timestamp when the bookshelf was created. */
	created_at: string | null,
};

/**  Settings specific to the bookshelf view. */
export type BookshelfSettings = {
	/**  The criteria used to sort items in the bookshelf. */
	sortOrder?: SortOrder,
	/**  The number of size to display in the bookshelf grid (index into a small/medium/large table). */
	gridSize?: number,
	/**  Whether to enable automatic horizontal scrolling for overflowing text. */
	enableAutoScroll?: boolean,
};

/**  Configuration for image caching and preloading. */
export type ComicCacheSettings = {
	/**  The number of pages to preload in each direction (forward and backward). */
	preloadPageCount?: number,
	/**  The maximum size of the image memory cache in MiB. */
	imageCacheSizeMib?: number,
};

/**  Configuration specific to reading comics (image-based content). */
export type ComicSettings = {
	/**  The reading direction (e.g., Right-to-Left for Japanese manga). */
	readingDirection?: Direction,
	/**  Whether to display pages side-by-side (two-page spread). */
	enableSpread?: boolean,
	/**  Whether to force the first page (cover) to display as a single page in spread mode. */
	showCoverAsSinglePage?: boolean,
	/**  Configuration for the Loupe (Magnifier) feature. */
	loupe?: LoupeSettings,
	/**  Configuration for image caching and preloading. */
	cache?: ComicCacheSettings,
};

/**
 *  The serialized shape of [`Error`] exposed to the frontend (`{ code, message }`).
 * 
 *  This mirrors the custom `Serialize` implementation above and exists solely to
 *  provide a `specta::Type` definition for `Error`, since the `Error` enum itself
 *  wraps foreign error types that cannot derive `specta::Type`. The exported TS type
 *  takes this struct's name, `CommandError`.
 */
export type CommandError = {
	/**  The stable, programmatic error code. */
	code: number,
	/**  The human-readable error message. */
	message: string,
};

/**  Represents the direction in which content should be read. */
export type Direction = 
/**  Right-to-Left (e.g., traditional Japanese manga). */
"rtl" | 
/**  Left-to-Right (e.g., western comics). */
"ltr";

/**  The result of getting entries in a container. */
export type EntriesResult = {
	/**  The entry names in the container. */
	entries: string[],
	/**  Whether the container is a directory. */
	is_directory: boolean,
	/**  Whether the container is an EPUB novel. */
	is_novel: boolean,
};

/**  Settings for the file navigator. */
export type FileNavigatorSettings = {
	/**  The default directory opened when clicking the Home button. */
	homeDirectory?: string,
	/**  The criteria used to sort files and directories. */
	sortOrder?: SortOrder,
	/**  Whether to automatically watch the current directory for file changes. */
	watchDirectoryChanges?: boolean,
};

/**  General application settings. */
export type GeneralSettings = {
	/**  The application's color theme. */
	theme?: AppTheme,
	/**  The font family used for the application's UI. */
	appFontFamily?: string,
	/**  Configuration for application logging. */
	log?: LogSettings,
	/**
	 *  A flexible map for toggling or configuring experimental features.
	 * 
	 *  Exported to TypeScript with `unknown` values: `serde_json::Value` is an inline,
	 *  recursive type the exporter cannot expand, and experimental flags are arbitrary.
	 */
	experimentalFeatures?: { [key in string]: unknown },
};

/**  Settings related to tracking user history. */
export type HistorySettings = {
	/**  Whether to record the user's reading history and progress. */
	recordReadingHistory?: boolean,
};

/**  Represents the algorithm used for resampling images. */
export type ImageResamplingMethod = ImageResamplingMethod_Serialize | ImageResamplingMethod_Deserialize;

/**  Represents the algorithm used for resampling images. */
export type ImageResamplingMethod_Deserialize = 
/**  Nearest Neighbor */
"nearest" | 
/**  Box Filter (formerly Gaussian) */
"box" | 
/**  Box Filter (formerly Gaussian) */
"gaussian" | 
/**  Bilinear Filter (formerly Triangle) */
"bilinear" | 
/**  Bilinear Filter (formerly Triangle) */
"triangle" | 
/**  Hamming Filter */
"hamming" | 
/**  Cubic Filter */
"catmullRom" | 
/**  Mitchell-Netravali Filter */
"mitchellNetravali" | 
/**  Lanczos with window 3 */
"lanczos3";

/**  Represents the algorithm used for resampling images. */
export type ImageResamplingMethod_Serialize = 
/**  Nearest Neighbor */
"nearest" | 
/**  Box Filter (formerly Gaussian) */
"box" | 
/**  Bilinear Filter (formerly Triangle) */
"bilinear" | 
/**  Hamming Filter */
"hamming" | 
/**  Cubic Filter */
"catmullRom" | 
/**  Mitchell-Netravali Filter */
"mitchellNetravali" | 
/**  Lanczos with window 3 */
"lanczos3";

/**  Represents the initial view shown when the app starts. */
export type InitialView = 
/**  Opens the reading interface. */
"reader" | 
/**  Opens the bookshelf / library interface. */
"bookshelf";

/**  Settings related to the application's layout. */
export type LayoutSettings = {
	/**  Settings for the side pane (tabs and visibility). */
	sidePane?: SidePaneSettings,
};

/**  Represents the severity level for application logs. */
export type LogLevel = "trace" | "debug" | "info" | "warn" | "error";

/**  Configuration for application logging. */
export type LogSettings = {
	/**  The minimum severity level to log. */
	level?: LogLevel,
};

/**  Configuration for the Loupe (Magnifier) feature. */
export type LoupeSettings = {
	/**  The magnification zoom level of the loupe (`1.0` = no magnification). */
	zoom?: number | null,
	/**  The radius (size) of the loupe. */
	radius?: number | null,
	/**  The keyboard shortcut key to toggle the loupe. */
	toggleKey?: string,
};

/**  Configuration specific to reading novels (text-based content). */
export type NovelSettings = {
	/**  The font family used for rendering the text. */
	fontFamily?: string,
	/**  The size of the font used for rendering the text. Fractional sizes are allowed. */
	fontSize?: number | null,
};

/**  Represents a book along with its reading state, specifically for books that have been opened. */
export type ReadBook = {
	/**  The unique identifier for the book. */
	id: number,
	/**  The unique file path or directory path of the book. */
	file_path: string,
	/**  The type of the item ('file' or 'directory'). */
	item_type: string,
	/**  The display name of the book. */
	display_name: string,
	/**  The total number of pages in the book. */
	total_pages: number,
	/**  The optional identifier of the series this book belongs to. */
	series_id: number | null,
	/**  The optional order index of the book within its series. */
	series_order: number | null,
	/**  The optional file path to the thumbnail image of the book. */
	thumbnail_path: string | null,
	/**  The last read page index. */
	last_read_page_index: number,
	/**
	 *  The timestamp when the book was last opened.
	 *  This is guaranteed to be present (not null) for read books.
	 */
	last_opened_at: string,
};

/**  Settings for the reading experience. */
export type ReaderSettings = ReaderSettings_Serialize | ReaderSettings_Deserialize;

/**  Settings for the reading experience. */
export type ReaderSettings_Deserialize = {
	/**  Configuration specific to reading comics/manga (images). */
	comic?: ComicSettings,
	/**  Configuration specific to reading novels (text). */
	novel?: NovelSettings,
	/**  Configuration for how pages and previews are rendered. */
	rendering?: RenderingSettings_Deserialize,
	/**  Behavior when paging past the last/first page of a book (auto-open adjacent book). */
	autoOpenAdjacentBook?: AutoOpenAdjacentBookMode,
};

/**  Settings for the reading experience. */
export type ReaderSettings_Serialize = {
	/**  Configuration specific to reading comics/manga (images). */
	comic: ComicSettings,
	/**  Configuration specific to reading novels (text). */
	novel: NovelSettings,
	/**  Configuration for how pages and previews are rendered. */
	rendering: RenderingSettings_Serialize,
	/**  Behavior when paging past the last/first page of a book (auto-open adjacent book). */
	autoOpenAdjacentBook: AutoOpenAdjacentBookMode,
};

/**  Represents the reading state of a specific book. */
export type ReadingState = {
	/**  The unique identifier for the associated book. */
	book_id: number,
	/**  The last read page index. */
	last_read_page_index: number,
	/**  The timestamp when the book was last opened. */
	last_opened_at: string | null,
};

/**  Configuration for image and document rendering. */
export type RenderingSettings = RenderingSettings_Serialize | RenderingSettings_Deserialize;

/**  Configuration for image and document rendering. */
export type RenderingSettings_Deserialize = {
	/**  Whether to generate and display thumbnail previews for pages. */
	enableThumbnailPreview?: boolean,
	/**  The maximum allowed height for an image before it is scaled down (`0` = unlimited). */
	maxImageHeight?: number,
	/**  The algorithm used for resampling (resizing) images. */
	imageResamplingMethod?: ImageResamplingMethod_Deserialize,
	/**  The vertical resolution used when rasterizing PDF pages to images. */
	pdfRenderResolutionHeight?: number,
};

/**  Configuration for image and document rendering. */
export type RenderingSettings_Serialize = {
	/**  Whether to generate and display thumbnail previews for pages. */
	enableThumbnailPreview: boolean,
	/**  The maximum allowed height for an image before it is scaled down (`0` = unlimited). */
	maxImageHeight: number,
	/**  The algorithm used for resampling (resizing) images. */
	imageResamplingMethod: ImageResamplingMethod_Serialize,
	/**  The vertical resolution used when rasterizing PDF pages to images. */
	pdfRenderResolutionHeight: number,
};

/**  Represents a series entity that groups multiple books together. */
export type Series = {
	/**  The unique identifier for the series. */
	id: number,
	/**  The unique name of the series. */
	name: string,
	/**  The timestamp when the series was created. */
	created_at: string,
};

/**
 *  A single-category settings change.
 * 
 *  The variant names the top-level category; the payload is a *partial* of that
 *  category (only the changed leaves), expressed as a raw JSON `Value`. The backend
 *  deep-merges this partial into the current settings, so untouched sibling leaves
 *  are preserved. The patch is deserialize-only; it is never serialized back.
 * 
 *  Each payload is exported to TypeScript as `unknown` (via `#[specta(type = ...)]`):
 *  `serde_json::Value` is registered as an *inline* type in specta, and its recursive
 *  shape cannot be inlined by the exporter. The frontend builds a typed partial and
 *  casts it to `SettingsPatch`, so the looser `unknown` boundary is sufficient.
 */
export type SettingsPatch = 
/**  A partial update to [`GeneralSettings`]. */
({ general: unknown }) & { bookshelf?: never; fileNavigator?: never; history?: never; layout?: never; reader?: never; startup?: never } | 
/**  A partial update to [`StartupSettings`]. */
({ startup: unknown }) & { bookshelf?: never; fileNavigator?: never; general?: never; history?: never; layout?: never; reader?: never } | 
/**  A partial update to [`BookshelfSettings`]. */
({ bookshelf: unknown }) & { fileNavigator?: never; general?: never; history?: never; layout?: never; reader?: never; startup?: never } | 
/**  A partial update to [`FileNavigatorSettings`]. */
({ fileNavigator: unknown }) & { bookshelf?: never; general?: never; history?: never; layout?: never; reader?: never; startup?: never } | 
/**  A partial update to [`ReaderSettings`]. */
({ reader: unknown }) & { bookshelf?: never; fileNavigator?: never; general?: never; history?: never; layout?: never; startup?: never } | 
/**  A partial update to [`HistorySettings`]. */
({ history: unknown }) & { bookshelf?: never; fileNavigator?: never; general?: never; layout?: never; reader?: never; startup?: never } | 
/**  A partial update to [`LayoutSettings`]. */
({ layout: unknown }) & { bookshelf?: never; fileNavigator?: never; general?: never; history?: never; reader?: never; startup?: never };

/**  Settings for the side pane. */
export type SidePaneSettings = {
	/**  Whether the side pane is hidden. */
	isHidden?: boolean,
	/**  The index of the active tab in the side pane. */
	tabIndex?: number,
};

/**  Represents the criteria used for sorting items. */
export type SortOrder = 
/**  Sort alphabetically by name, ascending (A-Z). */
"name_asc" | 
/**  Sort alphabetically by name, descending (Z-A). */
"name_desc" | 
/**  Sort by date, ascending (Oldest first). */
"date_asc" | 
/**  Sort by date, descending (Newest first). */
"date_desc";

/**  Settings related to the application's startup behavior. */
export type StartupSettings = {
	/**  The initial view presented to the user upon launch. */
	initialView?: InitialView,
	/**  Whether to automatically restore the last opened book/container on startup. */
	restoreLastBook?: boolean,
	/**  Whether to automatically check for updates on startup. */
	checkUpdateOnStartup?: boolean,
};

/**  Represents a tag entity used to categorize books. */
export type Tag = {
	/**  The unique identifier for the tag. */
	id: number,
	/**  The unique name of the tag. */
	name: string,
	/**  The color code of the tag (e.g., "#FF0000" for red). */
	color_code: string,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

