// This file is generated by `npm run gen:bindings`. Do not edit it manually.

/**
 * Stable, backend-defined error codes. Generated from the Rust `ErrorCode`
 * variants (`src-tauri/src/error.rs`), the single source of truth.
 */
export const ErrorCode = {
  unsupportedContainer: 10001,
  entryNotFound: 10002,
  pdfium: 10101,
  image: 80001,
  imageResize: 80101,
  unrar: 10301,
  zip: 10401,
  epub: 10501,
  epubArchive: 10502,
  io: 20001,
  path: 20101,
  tauri: 30001,
  rayonThreadPool: 30201,
  serdeJson: 40001,
  strumParse: 40101,
  parseInt: 40201,
  settings: 50001,
  settingsValidation: 50002,
  database: 70001,
  migration: 70101,
  other: 90001,
} as const;

/** Union of the backend error-code values. */
export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
