name: Bug Report
description: Create a report to help us improve RookReader
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide as much detail as possible to help us resolve the issue.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: Describe what went wrong...
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior.
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Open an zip file '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: Which operating system are you using?
      options:
        - Windows
        - Linux
        - macOS
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: RookReader Version
      description: e.g., v1.0.0 or the commit hash if building from source.
      placeholder: v1.0.0
    validations:
      required: true
  - type: textarea
    id: screenshots_context
    attributes:
      label: Screenshots & Additional Context
      description: If applicable, drag and drop screenshots here or add any other context about the problem.
    validations:
      required: false
